name: imhero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-231.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/img/
  
  fonts:
    - family: NotoSans

      fonts:
        - asset: asset/fonts/NotoSans-Black.ttf
          weight: 900
        - asset: asset/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: asset/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: asset/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: asset/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: asset/fonts/NotoSans-Thin.ttf
          weight: 100